### ISSUE TITLE
Sandbox PayPal Checkout Not Working

### ISSUE THREAD

**Issue by MSIH** [braintree/braintree-web-drop-in#795]
### General information

* SDK/Library version: 1.32.1
* Environment:  Sandbox 
* Browser and OS: Chrome windows 10

### Issue description
Braintree sandbox, linked to Paypal sandbox

Drop-in with Sandbox gives an error with flow being "checkout" but works with "vault"

```
braintree.dropin.create({
        authorization: clientToken,
        selector: '#bt-dropin',
        applePay: {
            displayName: 'Merchant Name',
            paymentRequest: {
                label: 'Localized Name',
                total: '9.99'
            },
            requiredBillingContactFields: ["postalAddress"]
        },
        paypal: {
           // flow: 'vault'
            flow: 'checkout',
            total: 11.11,
            currency: 'USD'
        },
```

Sandbox Web Site:
https://blazorbraintree20220131090307.azurewebsites.net/

1.  Select PayPal
2. Select Checkout Button
3. Error

console:
```
dropin.min.js:1 POST https://api.sandbox.braintreegateway.com/merchants/z2mjcs5c85np2wmv/client_api/v1/paypal_hermes/create_payment_resource 422

logger.js:63 ppxo_no_token_passed_to_payment {timestamp: 1643723294147, windowID: '45db6e23af', pageID: 'c696566e8f', prev_corr_ids: '', referer: 'blazorbraintree20220131090307.azurewebsites.net', …}

logger.js:63 ppxo_unhandled_error {stack: 'Error: No value passed to payment\n    at https://w…w.paypalobjects.com/api/checkout.min.js:2:131784)', errtype: '[object Error]', timestamp: 1643723294149, windowID: 'c7ef2896b6', pageID: 'd73ec56f0c', …}
country: "US"
env: "sandbox"
errtype: "[object Error]"
host: "www.sandbox.paypal.com"
lang: "en"
pageID: "d73ec56f0c"
path: "/smart/button"
prev_corr_ids: ""
referer: "https://blazorbraintree20220131090307.azurewebsites.net"
stack: "Error: No value passed to payment\n    at https://www.paypalobjects.com/api/checkout.min.js:2:821965\n    at e.o.dispatch (https://www.paypalobjects.com/api/checkout.min.js:2:19457)\n    at e.o.resolve (https://www.paypalobjects.com/api/checkout.min.js:2:18514)\n    at https://www.paypalobjects.com/api/checkout.min.js:2:18158\n    at Object.w.<computed> [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.min.js:2:130644)\n    at L (https://www.paypalobjects.com/api/checkout.min.js:2:131541)\n    at _ (https://www.paypalobjects.com/api/checkout.min.js:2:131784)"
timestamp: 1643723294149
uid: "uid_7aa4604ddd_mtm6ndy6nte"
ver: "4.0.334"
windowID: "c7ef2896b6"

types.js:121 Uncaught Error: No value passed to payment
    at component.jsx:460:35
    at e.o.dispatch (promise.js:171:42)
    at e.o.resolve (promise.js:97:14)
    at promise.js:44:30
    at Object.w.<computed> [as postrobot_message_response] (types.js:121:23)
    at L (index.js:114:35)
    at _ (index.js:140:5)
```

**Comment by crookedneighbor** [comment]
Can you try changing `total` to `amount`?

**Comment by MSIH** [comment]
That worked. Thanks
